version: "3.8"

services:
  # C++ Arbitrage Engine
  arbitrage-cpp:
    build:
      context: .
      dockerfile: Dockerfile.cpp
    container_name: arbitrage-cpp
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./config:/app/config:ro
      - ./logs:/var/log/arbitrage
    environment:
      - CONFIG_PATH=/app/config/production.yaml
      - LOG_LEVEL=INFO
      - THREAD_COUNT=8
      - ENABLE_THREAD_PINNING=true
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 512M
        reservations:
          cpus: "2"
          memory: 256M
    restart: unless-stopped
    depends_on:
      - timescaledb
      - redis
    networks:
      - arbitrage-net

  # TimescaleDB for time-series data storage
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: arbitrage-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=arbitrage
      - POSTGRES_USER=arbitrage_user
      - POSTGRES_PASSWORD=secure_password_123
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - timescale_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - arbitrage-net

  # Redis for caching and pub/sub
  redis:
    image: redis:7-alpine
    container_name: arbitrage-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    networks:
      - arbitrage-net

  # Nginx reverse proxy and load balancer
  nginx:
    image: nginx:alpine
    container_name: arbitrage-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-dashboard-index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - arbitrage-cpp
    networks:
      - arbitrage-net
    restart: unless-stopped

volumes:
  timescale_data:
  redis_data:

networks:
  arbitrage-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
